name: amigoz
description: A POS management tool.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2
  drift: ^2.17.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  uuid: ^4.5.3
  http: ^1.6.0
  image_picker: ^1.2.1
  mobile_scanner: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.17.0
  build_runner: ^2.14.1
  riverpod_generator: ^4.0.3
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/amigoz.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/amigoz.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/amigoz.png"
